### PR TITLE
Added CentOS nginx configuration

### PR DESCRIPTION
**Pull request by GONZALORUIZ**
Added CentOS nginx configuration
Only one storage account is created

### CODE REVIEW

**Comment by mahthi** [comment]
Here are a few requests for you Gonzalo

1) Send a new PR to this repo please - https://github.com/azure/azure-quickstart-templates
2) Here are some additional updates that would be great to do 
    • Update API Version for all Compute, Network and Storage resources to 2015-05-01-preview on all templates
    • Update Load Balancer API the latest design
    • Remove Default values for storage account etc., since it fails when using it with PowerShell
    • Update Source Image specification model to follow - https://github.com/azurermtemplates/azurermtemplates/blob/master/101-simple-vm-from-image/azuredeploy.json 
    • Add OsDisk specification even when creating from an image and use the "createoperation" element
    • Update DataDisk specification to have "CreatOption" element
    • Update SSH Keys to the SSH-2 RSA format

**Comment by GONZALORUIZ** [comment]
Good stuff Mahesh,
I have submitted a new PR to the new Repo with your recommendations, but I couldn't find an example for the SSH-2 RSA format. Also, did we manage to add the support for protectedSettings on time?

I will send an email with a couple of questions  / explanations.

**Comment by singhkays** [comment]
Thanks @GONZALORUIZ! left a few comments on the new repo PR

**Comment by singhkays** [comment]
closing this since this moved to new repo

**Pull request closed without merging**
