### PR TITLE
Updated SQL AlwaysOn README

### PR DESCRIPTION
**Pull request by ninarn**

### CODE REVIEW

**Comment by singhkays** [comment]
@ninarn We've moved to a new repo https://github.com/Azure/azure-quickstart-templates that is indexed on Azure.com. Can you please migrate this template over there. Thanks!

**Comment by mahthi** [comment]
Also, this template uses Classic resources, we are not going to push this to customers. We need to pull this template down completely. Ninar - can you please remove the template completely?

**Comment by ninarn** [comment]
+Omar

**Comment by singhkays** [comment]
Closing since we're not accepting PRs in this repo. Please send PRs to the new repo https://github.com/Azure/azure-quickstart-templates

**Pull request closed without merging**
