### PR TITLE
Initial commit - Apprenda

### PR DESCRIPTION
**Pull request by dutronlabs**
This will be the first of a few PRs, but wanted to setup the project structure in the main repo.

### CODE REVIEW

**Comment by singhkays** [comment]
@dutronlabs Can you include metadata descriptions tags on your parameters in azuredeploy.json. Thanks!

**Comment by dutronlabs** [comment]
will do. thanks!

**Comment by dutronlabs** [comment]
@singhkay this one is ready to go!

**Comment by singhkays** [comment]
@dutronlabs There's been a few changes since last time. We're moving to new repo here https://github.com/Azure/azure-quickstart-templates

Also we're deprecating the old API 2014-12-01-preview and moving to this new API 2015-05-01-preview. Here's a summary of changes needed 
https://github.com/azurermtemplates/azurermtemplates/blob/master/breaking-change.md

**Comment by singhkays** [comment]
closing, moved to new PR

**Pull request closed without merging**
