### PR TITLE
Install Scrapy in a single ubuntu machine

### PR DESCRIPTION
**Pull request by bingosummer**

### CODE REVIEW

**Comment by singhkays** [comment]
@bingosummer can you add metadata description tags to your parameters in azuredeploy.json file? Here's a starter template https://github.com/azurermtemplates/azurermtemplates/blob/master/100-starter-template-with-validation/azuredeploy.json

**Comment by bingosummer** [comment]
@singhkay I will add metadata and do some improvements. Thank you.

**Comment by bingosummer** [comment]
@singhkay The template is done. Could you please review it? Thank you.

**Comment by singhkays** [comment]
@bingosummer Looks good!

**Pull request merged**
