### PR TITLE
Adding Azure SQL DB ARM Template

### PR DESCRIPTION
**Pull request by vin-yu**
This ARM Template will create Azure SQL DB Logical Server, Database, Server Firewall Rule

### CODE REVIEW

**Comment by singhkays** [comment]
@TigerMint Can you add metadata description tags for your parameters in azuredeploy.json. Thanks!

**Comment by vin-yu** [comment]
added metatags

**Comment by singhkays** [comment]
@TigerMint Should have looked closer earlier. We also need a metadata.json file.

**Comment by vin-yu** [comment]
Added metadata json file

**Comment by singhkays** [comment]
@TigerMint We're moving to our new official repo. Can you move this template there and submit a PR? Thanks! https://github.com/Azure/azure-quickstart-templates

**Comment by singhkays** [comment]
@TigerMint working on moving, closing PR

**Pull request closed without merging**
